version: "3"
services:
 cassandra-node1:
  image: cassandra
  container_name: cassandra-node1
  hostname: cassandra-node1
  networks:
   - cassandra-network
  restart: always
  ports:
   - 9042:9042
   - 7199:7199
   - 7000:7000
   - 7001:7001
   - 9160:9160
  volumes:
   - cassandra-storage1:/var/lib/cassandra
  environment:
   CASSANDRA_CLUSTER_NAME: tpc
 cassandra-node2:
  image: cassandra
  container_name: cassandra-node2
  hostname: cassandra-node2
  networks:
   - cassandra-network
  restart: always
  volumes:
   - cassandra-storage2:/var/lib/cassandra
  environment:
   CASSANDRA_SEEDS: "cassandra-node1"
   CASSANDRA_CLUSTER_NAME: tpc
  links:
   - "cassandra-node1:node1"
  depends_on:
   - "cassandra-node1"
 cassandra-node3:
  image: cassandra
  container_name: cassandra-node3
  hostname: cassandra-node3
  networks:
   - cassandra-network
  restart: always
  volumes:
   - cassandra-storage3:/var/lib/cassandra
  environment:
   CASSANDRA_SEEDS: cassandra-node1
   CASSANDRA_CLUSTER_NAME: tpc
  links:
   - "cassandra-node1:node1"
  depends_on:
   - "cassandra-node2"
 cassandra-client:
  image: cassandra
  container_name: cassandra-client
  hostname: cassandra-client
  networks:
   - cassandra-network
  environment:
   CASSANDRA_CLUSTER_NAME: tpc
  links:
   - "cassandra-node1:node1"
   - "cassandra-node2:node2"
   - "cassandra-node3:node3"
  depends_on:
   - "cassandra-node3"
  command: /bin/bash
  stdin_open: true
  tty: true
networks:
 cassandra-network:
volumes:
 cassandra-storage1:
 cassandra-storage2:
 cassandra-storage3:
